config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root to: 'pages#home'

  scope '(:locale)', locale: /fr|en/ do
    get '/:locale' => 'events#index'
    root to: 'events#index'

    resources :events do
      # delete :destroy_current_user_participation, on: :member
      resources :participations, only: [:create]
      resource :participations, only: [] do
        delete :destroy_current_user_participation, on: :member
      end
    end
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :author, class_name: "User", inverse_of: "sent_events"
  has_many :participations, dependent: :destroy

  validates :title, presence: true

  after_create_commit :append_event
  after_update_commit :replace_event
  after_destroy_commit { broadcast_remove_to "events" }

  private

  def append_event
    broadcast_prepend_to "events", partial: "events/append_event", locals: { event: self, participations_count: 0 }
  end

  def replace_event
    broadcast_replace_to "events", target: "core_event_#{self.id}", partial: "events/event_core", locals: { event: self, participations_count: nil }
    broadcast_replace_to self, target: "core_event_#{self.id}", partial: "events/event_core", locals: { event: self, participations_count: nil }
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  before_action :set_event, only: [:edit]
  before_action :set_event_with_loading_participations, only: [:update, :show, :destroy]   # TODO : remove destroy and use set_event when just updating event with canceled: true

  def index
    @events = policy_scope(Event).includes(:author, participations: :user).order(created_at: :desc)

    @event= Event.new
  end

  def show
  end

  def new
    @event = current_user.sent_events.build
    authorize @event
  end

  def create
    @event = current_user.sent_events.build(event_params)
    authorize @event

    respond_to do |format|
      if @event.save
        # format.turbo_stream # { render turbo_stream: turbo_stream.prepend(:events, partial: "events/event", locals: {event: @event})}
        format.html { redirect_to events_path }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@event, partial: "events/form", locals: {event: @event})}
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@event, partial: "events/show_event", locals: { event: @event, participations_count: nil }) }
        format.html { redirect_to @event }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@event, partial: "events/form", locals: {event: @event})}
        format.html { render :edit }
      end
    end
  end

  def destroy
    @event.destroy

    redirect_to events_path
  end

  private

  def set_event
    @event = Event.includes(:author).find(params[:id])
    authorize @event
  end

  def set_event_with_loading_participations
    @event = Event.includes(:author, participations: :user).find(params[:id])
    authorize @event
  end

  def event_params
    params.require(:event).permit(:author, :title, :description)
  end
end

app/helpers/event_helper.rb
module EventHelper 
  def event_status(event)
    if policy(event).destroy?
      "owned"
    elsif policy(event).destroy_current_user_participation?
      "accepted"
    else
      "waiting"
    end
  end
end

app/views/events/_append_event.html.erb
<%= turbo_frame_tag dom_id(event) do %>
  <div class="border border-blue-600 rounded mt-3 p-3 card" data-controller="event">

    <%= render "events/event_core", event: event, participations_count: participations_count %>

    <%= render "events/links/accept_decline", event: event, participation: event.participations.new %>

  </div>
<% end %>

app/views/events/_event.html.erb
<%= turbo_frame_tag dom_id(event) do %>
  <div class="border rounded mt-3 p-3 card border-blue-600" data-controller="event" data-event-status-value=<%= event_status(event) %>>

    <%= render "events/event_core", event: event, participations_count: participations_count %>

    <% if policy(event).destroy_current_user_participation? %>
      <%= render "events/links/cancel_decline", event: event %>
    <% elsif current_user && (event.author != current_user) %>
      <%= render "events/links/accept_decline", event: event, participation: event.participations.new %>
    <% end %>

  </div>
<% end %>

app/views/events/_event_core.html.erb
<%= turbo_frame_tag "core_#{dom_id(event)}" do %>
  <%= link_to event_path(event), "data-turbo-frame": "_top" do %>
  <div class="border border-blue-600 rounded mt-3 p-3 bg-gray-200">
    <div class="text-sm flex justify-between px-1 rounded bg-orange-100">
      <p class="italic"><%= l(event.created_at, format: :short) %></p>
      <p class="italic"><%= event.author.name %></p>
    </div>

    <p class="text-lg font-bold mt-3"><%= event.title %></p>
    <p><%= event.description %></p>
  </div>
  <% end %>

  <div id="<%= dom_id(event) %>_participations" class="border border-blue-600 rounded mt-3 p-3 bg-orange-300">
    <p class="text-sm italic px-1 mb-1 rounded bg-orange-700">Participants : <span id="<%= dom_id(event) %>_participations_count"><%= participations_count || (event.participations.size + event.participations.sum(&:additional_participations_number)) %></span></p>
    <%= render event.participations if !participations_count %>
  </div>
<% end %>

app/views/events/_form.html.erb
<%= simple_form_for event,
  html: { id: dom_id(event) },
  data: { controller: "form", action: "turbo:submit-end->form#reset" } do |f| %>

  <div class="border rounded p-3 bg-white">
    <div id="event_form_fields">
      <%= f.input :title, label: false, placeholder: "* Ajoutez un évènement", required: true, input_html: {class: "rounded min-w-full mt-2"}  %>
      <%= f.input :description, label: false, placeholder: "Ajoutez une description", input_html: {class: "rounded min-w-full mt-2"}  %>
    </div>
    <div class="flex justify-between mt-2">
      <%= f.submit "Envoyer", class: "border border-blue-600  rounded bg-blue-200 p-2" %>
      <% if event.persisted? %>
        <%= link_to "Annuler", event_path(event), class: "border border-blue-600 rounded bg-gray-200 p-2" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/events/_show_event.html.erb
<%= turbo_frame_tag dom_id(event) do %>
  <div class="border border-blue-600 rounded mt-3 p-3 card" data-controller="event" data-event-status-value=<%= event_status(event) %>>
    <%= render "events/event_core", event: event, participations_count: participations_count %>

    <% if policy(event).destroy? %>
      <div class="flex justify-between mt-4">
        <%= link_to "Modifier", edit_event_path(event), class: "border border-blue-600 rounded bg-gray-200 p-1" %>
        <%= button_to "Supprimer", event_path(event), method: :delete, class: "border border-blue-600 cursor-pointer rounded bg-gray-100 p-1", "data-turbo-frame": "_top" %>
      </div>
    <% elsif policy(event).destroy_current_user_participation? %>
      <%= render "events/links/cancel_decline", event: event %>
    <% elsif current_user && (event.author != current_user) %>
      <%= render "events/links/accept_decline", event: event, participation: event.participations.new %>
    <% end %>

  </div>
<% end %>

app/views/events/edit.html.erb
<%= turbo_frame_tag @event do %>
  <div class="mt-4">
    <%= render 'form', event: @event %>
  </div>
<% end %>

app/views/events/index.html.erb
<div class="flex flex-col">

  <%= link_to "EMETTRE", new_event_path, class: "text-center font-bold rounded border-2  border-blue-600 bg-orange-500 p-2 mt-5" %>

  <%= turbo_stream_from "events" %>

  <div id="events">
    <%= render @events, participations_count: @participations_count  %>
  </div>

</div>

app/views/events/new.html.erb
<%= turbo_frame_tag "event_form", class: "mt-5", target: "_top" do %>
  <%= render "events/form", event: @event %>
<% end %>

app/views/events/show.html.erb
<%= turbo_stream_from @event %>

<div class="flex flex-col w-full">
  <%= render "events/show_event", event: @event, participations_count: @participations_count %>
</div>