config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root to: 'pages#home'

  scope '(:locale)', locale: /fr|en/ do
    get '/:locale' => 'events#index'
    root to: 'events#index'

    resources :events do
      # delete :destroy_current_user_participation, on: :member
      resources :participations, only: [:create]
      resource :participations, only: [] do
        delete :destroy_current_user_participation, on: :member
      end
    end
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :author, class_name: "User", inverse_of: "sent_events"
  has_many :participations, dependent: :destroy

  validates :title, presence: true

  after_create_commit :append_event
  after_update_commit :replace_event
  after_destroy_commit { broadcast_remove_to "events" }

  private

  def append_event
    broadcast_prepend_to "events", partial: "events/append_event", locals: { event: self, participations_count: 0 }
  end

  def replace_event
    broadcast_replace_to "events", target: "core_event_#{self.id}", partial: "events/event_core", locals: { event: self, participations_count: nil }
    broadcast_replace_to self, target: "core_event_#{self.id}", partial: "events/event_core", locals: { event: self, participations_count: nil }
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  before_action :set_event, only: [:edit]
  before_action :set_event_with_loading_participations, only: [:update, :show, :destroy]   # TODO : remove destroy and use set_event when just updating event with canceled: true

  def index
    @events = policy_scope(Event).includes(:author, participations: :user).order(created_at: :desc)

    @event= Event.new
  end

  def show
  end

  def new
    @event = current_user.sent_events.build
    authorize @event
  end

  def create
    @event = current_user.sent_events.build(event_params)
    authorize @event

    respond_to do |format|
      if @event.save
        # format.turbo_stream # { render turbo_stream: turbo_stream.prepend(:events, partial: "events/event", locals: {event: @event})}
        format.html { redirect_to events_path }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@event, partial: "events/form", locals: {event: @event})}
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@event, partial: "events/show_event", locals: { event: @event, participations_count: nil }) }
        format.html { redirect_to @event }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@event, partial: "events/form", locals: {event: @event})}
        format.html { render :edit }
      end
    end
  end

  def destroy
    @event.destroy

    redirect_to events_path
  end

  private

  def set_event
    @event = Event.includes(:author).find(params[:id])
    authorize @event
  end

  def set_event_with_loading_participations
    @event = Event.includes(:author, participations: :user).find(params[:id])
    authorize @event
  end

  def event_params
    params.require(:event).permit(:author, :title, :description)
  end
end

app/helpers/event_helper.rb
module EventHelper 
  def event_status(event)
    if policy(event).destroy?
      "owned"
    elsif policy(event).destroy_current_user_participation?
      "accepted"
    else
      "waiting"
    end
  end
end

app/views/events/links/_accept_decline.html.erb
<div id="<%= dom_id(event) %>_links" class="flex justify-center mt-3" data-event-target="waiting">
  <%= simple_form_for [event, participation],
  html: { id: dom_id(participation) },
  data: { controller: "form", action: "turbo:submit-end->form#reset", "turbo-frame": "_top" } do |f| %>

    <div class="flex justify-around">
      <%= f.submit "Je viens", class: "border-2 border-blue-600 rounded text-black bg-blue-400 p-1" %>
      <p class="ml-2 mr-1 mt-2">avec +</p>
      <div id="participation_form_fields">
        <%= f.input :additional_participations_number, label: false, placeholder: "0", required: false, input_html: {class: "rounded w-16"}  %>
      </div>
    </div>
  <% end %>
</div>

app/views/events/links/_cancel_decline.html.erb
<div id="<%= dom_id(event) %>_links" class="flex justify-center mt-3" data-event-target="accepted">
  <%= button_to "Annuler", destroy_current_user_participation_event_participations_path(event), method: :delete, class: "border border-blue-600 cursor-pointer rounded bg-gray-100 p-1" %>
</div>